SNOWFLAKE-ACCOUNT:https://vvtgfkw-sales_account.snowflakecomputing.com
SNOWFLAKE-USER:sales_admin
SNOWFLAKE-PASSWORD:<SYSTEM_USER_PAT>
SNOWFLAKE-ROLE:account_admin
SNOWFLAKE-WAREHOUSE:APP_WH
SNOWFLAKE-DATABASE:APPSDB
SNOWFLAKE-SCHEMA:APPS
CHANGE-HISTORY-TABLE:METADATA.SCHEMACHANGE.CHANGE_HISTORY 
