SNOWFLAKE-ACCOUNT:https://vvtgfkw-sales_account.snowflakecomputing.com
SNOWFLAKE-USER:sales_admin
SNOWFLAKE-PASSWORD:eyJraWQiOiI4OTM4NDQ2MDI5MyIsImFsZyI6IkVTMjU2In0.eyJwIjoiMzQ5MTU3ODkyOjM0OTE1Nzg5MiIsImlzcyI6IlNGOjEwMTIiLCJleHAiOjE3NzY2MTkyMzh9.bNMNFz2XHHGAnC3wymnD6cRNy24qFDRnHOi4fG06krckKvvPbAvpCzthSeM83gePRqvO6yweD5th3uKwC7zdcQ
SNOWFLAKE-ROLE:accountadmin
SNOWFLAKE-WAREHOUSE:APP_WH
SNOWFLAKE-DATABASE:APPDB
SNOWFLAKE-SCHEMA:APPS
CHANGE-HISTORY-TABLE:METADATA.SCHEMACHANGE.CHANGE_HISTORY 
