SNOWFLAKE-ACCOUNT: "https://vvtgfkw-sales_account.snowflakecomputing.com"
SNOWFLAKE-USER: "sales_admin"
SNOWFLAKE-ROLE: "accountadmin"
SNOWFLAKE-WAREHOUSE: "APP_WH"
SNOWFLAKE-DATABASE: "APPDB"
SNOWFLAKE-SCHEMA: "APPS"
CHANGE-HISTORY-TABLE: "METADATA.SCHEMACHANGE.CHANGE_HISTORY"
create-change-history-table: true
